/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_admin_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/approvals/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_admin_approvals__user_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/approvals/{user_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_admin_approvals__user_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Stats */
        get: operations["dashboard_stats_admin_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facilities */
        get: operations["list_facilities_admin_facilities_get"];
        put?: never;
        /** Create Facility */
        post: operations["create_facility_admin_facilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/facilities/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Facility Assistant
         * @description 시설 AI 도우미(FR-FAC-02) — 유사 장애·이력 근거로 가능 원인 후보 제시(단정 금지).
         *
         *     answer_question 재사용(시설 프롬프트만 주입) — 레지스트리·마스킹·스텝 상한·폴백·영속은
         *     /assistant/ask와 공유. ctx.roles(MANAGER/FACILITY)가 시설 도구 노출을 결정한다.
         */
        post: operations["facility_assistant_admin_facilities_assistant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/facilities/{facility_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Facility */
        get: operations["get_facility_admin_facilities__facility_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Facility */
        patch: operations["patch_facility_admin_facilities__facility_id__patch"];
        trace?: never;
    };
    "/admin/facilities/{facility_id}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Incident */
        post: operations["create_incident_admin_facilities__facility_id__incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/facilities/{facility_id}/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Maintenance */
        post: operations["create_maintenance_admin_facilities__facility_id__maintenance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fees */
        get: operations["list_fees_admin_fees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fees/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Fees */
        post: operations["upload_fees_admin_fees_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fees/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload */
        get: operations["get_upload_admin_fees_uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fees/uploads/{upload_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Fees */
        post: operations["apply_fees_admin_fees_uploads__upload_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/inquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Inquiries */
        get: operations["list_admin_inquiries_admin_inquiries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/inquiries/{inquiry_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Inquiry */
        post: operations["assign_inquiry_admin_inquiries__inquiry_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/inquiries/{inquiry_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Inquiry Status */
        post: operations["change_inquiry_status_admin_inquiries__inquiry_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Notice */
        post: operations["publish_notice_admin_notices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notices/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft */
        post: operations["create_draft_admin_notices_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notices/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_admin_notices_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Review Queue
         * @description 검수 대상 assistant 답변 목록. 신뢰도 낮은 순(nulls last)→오래된 순 정렬.
         */
        get: operations["list_review_queue_admin_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/review-queue/{message_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Review
         * @description 승인/반려 결정 기록(사후) — review_status·reviewed_by/at·note 갱신. 부수효과 없음.
         */
        post: operations["decide_review_admin_review_queue__message_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roster/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Roster */
        post: operations["upload_roster_admin_roster_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["google_login_auth_google_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 멱등 — 쿠키 유무와 무관하게 204. 쿠키 있으면 세션 revoke + 쿠키 제거.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Document */
        patch: operations["patch_document_documents__document_id__patch"];
        trace?: never;
    };
    "/documents/{document_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Document */
        post: operations["reindex_document_documents__document_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Fees */
        get: operations["get_my_fees_fees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fees/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain */
        post: operations["explain_fees_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Inquiries */
        get: operations["list_my_inquiries_inquiries_get"];
        put?: never;
        /** Create Inquiry */
        post: operations["create_inquiry_inquiries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inquiries/{inquiry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inquiry */
        get: operations["get_inquiry_inquiries__inquiry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inquiries/{inquiry_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inquiry Events */
        get: operations["list_inquiry_events_inquiries__inquiry_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 계정 상태 무관 — 온보딩·pending 등 모든 상태에서 화면 분기의 단일 출처.
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notices */
        get: operations["list_notices_notices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notices/{notice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notice */
        get: operations["get_notice_notices__notice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Notifications
         * @description 본인 알림 최신순. 소유권 필터가 쿼리에 박힘 — 파라미터로 우회 불가(규칙 4).
         */
        get: operations["list_my_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Read
         * @description 읽음 스탬프 — 본인 알림만. 이미 읽었으면 기존 시각 유지(멱등).
         */
        post: operations["mark_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Profile */
        post: operations["submit_profile_onboarding_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminFeeListOut */
        AdminFeeListOut: {
            /** Household Count */
            household_count: number;
            /** Households */
            households: components["schemas"]["AdminFeeRow"][];
            /** Period */
            period: string;
            /** Total Sum */
            total_sum: number;
        };
        /** AdminFeeRow */
        AdminFeeRow: {
            /** Building Name */
            building_name: string;
            /** Floor */
            floor: number;
            /**
             * Household Id
             * Format: uuid
             */
            household_id: string;
            /** Total */
            total: number;
            /** Unit No */
            unit_no: number;
        };
        /** AiStats */
        AiStats: {
            /** Answer Rate */
            answer_rate: number | null;
            /** Avg Token Input */
            avg_token_input: number | null;
            /** Avg Token Output */
            avg_token_output: number | null;
            /** Fallback Rate */
            fallback_rate: number | null;
            /** Needs Review Rate */
            needs_review_rate: number | null;
            /** Query Count */
            query_count: number;
        };
        /** ApprovalListOut */
        ApprovalListOut: {
            /** Items */
            items: components["schemas"]["ApprovalOut"][];
        };
        /** ApprovalOut */
        ApprovalOut: {
            /** Building Name */
            building_name: string | null;
            /** Floor */
            floor: number | null;
            /** Name Masked */
            name_masked: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Roster Matched */
            roster_matched: boolean;
            /** Unit No */
            unit_no: number | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Question */
            question: string;
        };
        /** AssignIn */
        AssignIn: {
            /**
             * Assignee User Id
             * Format: uuid
             */
            assignee_user_id: string;
        };
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /** File */
            file: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "규약" | "회의록" | "공지" | "지침" | "매뉴얼";
            /** Title */
            title: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "ALL" | "RESIDENT" | "ADMIN" | "COUNCIL";
        };
        /** Body_upload_fees_admin_fees_uploads_post */
        Body_upload_fees_admin_fees_uploads_post: {
            /** File */
            file: string;
        };
        /** Body_upload_roster_admin_roster_upload_post */
        Body_upload_roster_admin_roster_upload_post: {
            /** File */
            file: string;
        };
        /**
         * BudgetStats
         * @description 단지 일일 토큰 예산 대비 사용량(H4-4, NFR-COST-01). 경고만 — 차단 없음.
         */
        BudgetStats: {
            /** Budget */
            budget: number;
            /** Enabled */
            enabled: boolean;
            /** Exceeded */
            exceeded: boolean;
            /** Used Today */
            used_today: number;
        };
        /** CacheStats */
        CacheStats: {
            /** Hit Rate */
            hit_rate: number | null;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
        };
        /** ConsentIn */
        ConsentIn: {
            /** Granted */
            granted: boolean;
            /** Purpose */
            purpose: string;
        };
        /** DashboardStatsOut */
        DashboardStatsOut: {
            ai: components["schemas"]["AiStats"];
            budget: components["schemas"]["BudgetStats"];
            cache: components["schemas"]["CacheStats"];
            /** Days */
            days: number;
            /** Facilities */
            facilities: {
                [key: string]: number;
            };
            /** Inquiries */
            inquiries: {
                [key: string]: number;
            };
        };
        /** DecideIn */
        DecideIn: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject";
            /** Note */
            note?: string | null;
        };
        /** DocumentListOut */
        DocumentListOut: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Index Status
             * @enum {string}
             */
            index_status: "pending" | "indexing" | "indexed" | "failed";
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "규약" | "회의록" | "공지" | "지침" | "매뉴얼";
            /** Title */
            title: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "ALL" | "RESIDENT" | "ADMIN" | "COUNCIL";
        };
        /**
         * DocumentPatchIn
         * @description 부분 수정 — 지정한 필드만 갱신(둘 다 None이면 no-op 아님, 422).
         */
        DocumentPatchIn: {
            /** Title */
            title?: string | null;
            /** Visibility */
            visibility?: ("ALL" | "RESIDENT" | "ADMIN" | "COUNCIL") | null;
        };
        /** DocumentUploadOut */
        DocumentUploadOut: {
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Index Status
             * @enum {string}
             */
            index_status: "pending" | "indexing" | "indexed" | "failed";
        };
        /** DraftDetailOut */
        DraftDetailOut: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Keywords */
            keywords: string[];
            /** Notice Id */
            notice_id: string | null;
            /** Review Status */
            review_status: string;
            /** Title */
            title: string;
        };
        /** DraftOut */
        DraftOut: {
            /** Body */
            body: string;
            /** Citations */
            citations: components["schemas"]["NoticeCitationOut"][];
            /** Confidence */
            confidence: number;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Title */
            title: string;
        };
        /** DraftRequestIn */
        DraftRequestIn: {
            /** Keywords */
            keywords: string[];
        };
        /** FacilityCreateIn */
        FacilityCreateIn: {
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Next Check At */
            next_check_at?: string | null;
            /**
             * Status
             * @default normal
             * @enum {string}
             */
            status: "normal" | "check" | "fault" | "risk";
            /** Type */
            type?: string | null;
        };
        /** FacilityDetailOut */
        FacilityDetailOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Incidents */
            incidents: components["schemas"]["IncidentOut"][];
            /** Location */
            location: string | null;
            /** Maintenance Logs */
            maintenance_logs: components["schemas"]["MaintenanceOut"][];
            /** Name */
            name: string;
            /** Next Check At */
            next_check_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "normal" | "check" | "fault" | "risk";
            /** Type */
            type: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FacilityListOut */
        FacilityListOut: {
            /** Items */
            items: components["schemas"]["FacilityOut"][];
            /** Total */
            total: number;
        };
        /** FacilityOut */
        FacilityOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location */
            location: string | null;
            /** Name */
            name: string;
            /** Next Check At */
            next_check_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "normal" | "check" | "fault" | "risk";
            /** Type */
            type: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FacilityPatchIn */
        FacilityPatchIn: {
            /** Location */
            location?: string | null;
            /** Name */
            name?: string | null;
            /** Next Check At */
            next_check_at?: string | null;
            /** Status */
            status?: ("normal" | "check" | "fault" | "risk") | null;
            /** Type */
            type?: string | null;
        };
        /** FeeApplyOut */
        FeeApplyOut: {
            /** Applied */
            applied: number;
            /** Period */
            period: string;
            /** Status */
            status: string;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
        };
        /** FeeExplainRequest */
        FeeExplainRequest: {
            /** Period */
            period: string;
        };
        /** FeeOut */
        FeeOut: {
            /** Breakdown */
            breakdown: {
                [key: string]: number;
            } | null;
            /** Period */
            period: string;
            /** Prev Total */
            prev_total: number | null;
            /** Total */
            total: number | null;
        };
        /** FeePreviewRow */
        FeePreviewRow: {
            /** Breakdown */
            breakdown: {
                [key: string]: number;
            };
            /** Building Name */
            building_name: string;
            /** Floor */
            floor: number;
            /** Total */
            total: number;
            /** Unit No */
            unit_no: number;
        };
        /** FeeRowErrorOut */
        FeeRowErrorOut: {
            /** Reason */
            reason: string;
            /** Row */
            row: number;
        };
        /** FeeUploadDetailOut */
        FeeUploadDetailOut: {
            /** Errors */
            errors: components["schemas"]["FeeRowErrorOut"][];
            /** Period */
            period: string | null;
            /** Row Count */
            row_count: number | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
        };
        /** FeeUploadOut */
        FeeUploadOut: {
            /** Errors */
            errors: components["schemas"]["FeeRowErrorOut"][];
            /** Period */
            period: string;
            /** Preview */
            preview: components["schemas"]["FeePreviewRow"][];
            /** Row Count */
            row_count: number;
            /** Status */
            status: string;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            /** Valid Rows */
            valid_rows: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IncidentCreateIn */
        IncidentCreateIn: {
            /** Occurred At */
            occurred_at?: string | null;
            /** Resolution */
            resolution?: string | null;
            /** Root Cause */
            root_cause?: string | null;
            /** Symptom */
            symptom: string;
        };
        /** IncidentOut */
        IncidentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Occurred At */
            occurred_at: string | null;
            /** Resolution */
            resolution: string | null;
            /** Root Cause */
            root_cause: string | null;
            /** Symptom */
            symptom: string;
        };
        /** InquiryCreateIn */
        InquiryCreateIn: {
            /** Body */
            body: string;
            /** Category Id */
            category_id?: string | null;
            /** Title */
            title: string;
        };
        /** InquiryEventListOut */
        InquiryEventListOut: {
            /** Items */
            items: components["schemas"]["InquiryEventOut"][];
        };
        /** InquiryEventOut */
        InquiryEventOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Type
             * @enum {string}
             */
            type: "created" | "ai_classified" | "assigned" | "status_changed" | "comment";
        };
        /** InquiryListOut */
        InquiryListOut: {
            /** Items */
            items: components["schemas"]["InquiryOut"][];
        };
        /** InquiryOut */
        InquiryOut: {
            /** Ai Priority */
            ai_priority: ("urgent" | "normal" | "low") | null;
            /** Ai Suggested Category Id */
            ai_suggested_category_id: string | null;
            /** Assignee User Id */
            assignee_user_id: string | null;
            /**
             * Author User Id
             * Format: uuid
             */
            author_user_id: string;
            /** Body */
            body: string;
            /** Category Id */
            category_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "assigned" | "in_progress" | "done";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MaintenanceCreateIn */
        MaintenanceCreateIn: {
            /** Parts */
            parts?: {
                [key: string]: unknown;
            } | null;
            /** Performed At */
            performed_at?: string | null;
            /** Performer */
            performer?: string | null;
            /** Work */
            work: string;
        };
        /** MaintenanceOut */
        MaintenanceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parts */
            parts: {
                [key: string]: unknown;
            } | null;
            /** Performed At */
            performed_at: string | null;
            /** Performer */
            performer: string | null;
            /** Work */
            work: string;
        };
        /** MeOut */
        MeOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "user" | "onboarding";
            /** Roles */
            roles: string[];
            /** Status */
            status: string;
            /** Tenant Id */
            tenant_id: string | null;
            /** User Id */
            user_id: string | null;
        };
        /** NoticeCitationOut */
        NoticeCitationOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Quote */
            quote: string;
        };
        /** NoticeListOut */
        NoticeListOut: {
            /** Items */
            items: components["schemas"]["NoticeOut"][];
        };
        /** NoticeOut */
        NoticeOut: {
            /** Audience */
            audience: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Published At */
            published_at: string | null;
            /** Published By */
            published_by: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "retracted" | "superseded";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** NotificationListOut */
        NotificationListOut: {
            /** Items */
            items: components["schemas"]["NotificationOut"][];
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Total */
            total: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Body */
            body: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Link */
            link: string | null;
            /** Read At */
            read_at: string | null;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "notice" | "inquiry_status" | "approval" | "system";
        };
        /** ProfileIn */
        ProfileIn: {
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Building Name */
            building_name: string;
            /** Consents */
            consents: components["schemas"]["ConsentIn"][];
            /** Floor */
            floor: number;
            /** Invite Code */
            invite_code: string;
            /** Name */
            name: string;
            /** Unit No */
            unit_no: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Roster Matched */
            roster_matched: boolean;
            /** Status */
            status: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** PublishIn */
        PublishIn: {
            /**
             * Audience
             * @default ALL
             * @constant
             */
            audience: "ALL";
            /** Body */
            body: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Title */
            title: string;
        };
        /** RejectIn */
        RejectIn: {
            /** Reason */
            reason: string;
        };
        /** ReviewCitationOut */
        ReviewCitationOut: {
            /** Document Title */
            document_title: string | null;
            /** Quote */
            quote: string | null;
        };
        /** ReviewItemOut */
        ReviewItemOut: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["ReviewCitationOut"][];
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Question */
            question: string | null;
            /** Review Note */
            review_note: string | null;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "needs_review" | "approved" | "rejected";
            /** Reviewed At */
            reviewed_at: string | null;
            /** Status */
            status: string | null;
        };
        /** ReviewListOut */
        ReviewListOut: {
            /** Items */
            items: components["schemas"]["ReviewItemOut"][];
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Total */
            total: number;
        };
        /** RosterRowError */
        RosterRowError: {
            /** Reason */
            reason: string;
            /** Row */
            row: number;
        };
        /** RosterUploadOut */
        RosterUploadOut: {
            /** Applied */
            applied: number;
            /** Errors */
            errors: components["schemas"]["RosterRowError"][];
            /** Marked Inactive */
            marked_inactive: number;
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
        };
        /** StatusChangeIn */
        StatusChangeIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "assigned" | "in_progress" | "done";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_approvals_admin_approvals_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_admin_approvals__user_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_admin_approvals__user_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_stats_admin_dashboard_stats_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facilities_admin_facilities_get: {
        parameters: {
            query?: {
                status?: ("normal" | "check" | "fault" | "risk") | null;
                type?: string | null;
                page?: number;
                limit?: number;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_facility_admin_facilities_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacilityCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facility_assistant_admin_facilities_assistant_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facility_admin_facilities__facility_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                facility_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_facility_admin_facilities__facility_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                facility_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacilityPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_incident_admin_facilities__facility_id__incidents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                facility_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_maintenance_admin_facilities__facility_id__maintenance_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                facility_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fees_admin_fees_get: {
        parameters: {
            query: {
                period: string;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeeListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_fees_admin_fees_uploads_post: {
        parameters: {
            query: {
                period: string;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_fees_admin_fees_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_admin_fees_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                upload_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeUploadDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_fees_admin_fees_uploads__upload_id__apply_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                upload_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_inquiries_admin_inquiries_get: {
        parameters: {
            query?: {
                status?: ("received" | "assigned" | "in_progress" | "done") | null;
                category_id?: string | null;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_inquiry_admin_inquiries__inquiry_id__assign_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                inquiry_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_inquiry_status_admin_inquiries__inquiry_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                inquiry_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_notice_admin_notices_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_admin_notices_drafts_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_admin_notices_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_queue_admin_review_queue_get: {
        parameters: {
            query?: {
                status?: "needs_review" | "approved" | "rejected";
                page?: number;
                limit?: number;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_review_admin_review_queue__message_id__decide_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_roster_admin_roster_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_roster_admin_roster_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_assistant_ask_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_callback_auth_google_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_auth_google_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: {
                index_status?: ("pending" | "indexing" | "indexed" | "failed") | null;
                q?: string | null;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_document_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_document_documents__document_id__reindex_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_fees_fees_get: {
        parameters: {
            query: {
                period: string;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_fees_explain_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeeExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_my_inquiries_inquiries_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_inquiry_inquiries_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InquiryCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inquiry_inquiries__inquiry_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                inquiry_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inquiry_events_inquiries__inquiry_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                inquiry_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryEventListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notices_notices_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notice_notices__notice_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                notice_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_notifications_notifications_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path: {
                notification_id: string;
            };
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_profile_onboarding_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                liviq_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
