/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Question */
            question: string;
        };
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /** File */
            file: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "규약" | "회의록" | "공지" | "지침" | "매뉴얼";
            /** Title */
            title: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "ALL" | "RESIDENT" | "ADMIN" | "COUNCIL";
        };
        /** DocumentListOut */
        DocumentListOut: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Index Status
             * @enum {string}
             */
            index_status: "pending" | "indexing" | "indexed" | "failed";
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "규약" | "회의록" | "공지" | "지침" | "매뉴얼";
            /** Title */
            title: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "ALL" | "RESIDENT" | "ADMIN" | "COUNCIL";
        };
        /** DocumentUploadOut */
        DocumentUploadOut: {
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Index Status
             * @enum {string}
             */
            index_status: "pending" | "indexing" | "indexed" | "failed";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_assistant_ask_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-tenant-id"?: string | null;
                "x-dev-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
